### ISSUE TITLE
INI-Datei: Verhalten passt nicht zur Beschreibung

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#1]
In der Beschreibung steht bei SchulabschlussQuelle: Sollte kein Abschluss gefunden werden, so wird beim Zeugnisdruck gefragt.
Diese Abfrage erfolgt allerdings nur, wenn AlteAbschluesseErfragen=J gesetzt ist. Entweder muss man die Programmierung anpassen oder das in der Beschreibung ergänzen.

**Comment by M-Plu** [comment]
IN welcher Anlage ist das so?

**Comment by mueller-falko** [comment]
In Anlage 4 und 6. In der Programmierung von "AbschlussErmitteln" ist die Abfrage des Abschlusses meines Erachtens immer an AlteAbschluesseErfragen oder SchulabschlussQuelle = 'F' gekoppelt. In anderen Fällen erscheint sie nicht.

**Comment by M-Plu** [comment]
Ich denke es ist konsequent, so wie es umgesetzt ist. Bei H wird im Halbjahr gesucht. Ist da nichts, muss es ein alter Abschluss sein und nach dem sollte nur auf Wunsch gefragt werden.

Da müsste dann die Beschreibung angepasst werden. Das mache ich.

Wie siehst du das bei den Sek-I Zeugnissen. Müssten wir da noch was anpassen?

**Comment by FPfotenhauer** [comment]
Kann das Issue geschlossen werden?

**Comment by M-Plu** [comment]
Für die Sek-II ja. Meine Frage bezog sich darauf, ob man den neuen Parameter auch in der Sek-I einpflegen sollte.
