### ISSUE TITLE
Schulnummer im Schulkopf

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#10]
In den Sek 1 Zeugnissen hatten wir die Schulnummer in den Schulkopf eingebaut. Sie waren auch in den alten SII-Zeugnissen vorhanden. Meines Wissens nach sind sind sie auch verpflichtend!?!?

**Comment by M-Plu** [comment]
In der Sek-I fordert APO-S I VV 7.1.1 die Angabe der Schulnummer unter dem Schulkopf. Das gibt es in der APO-GOSt oder einer anderen mir bekannten Verordnung, die auch für die Sek-II gilt, nicht. Dafür fordern die Anhänge der APO-GOSt die Schulnummer im Fuß des Zeugnisses (am Ende).
