### ISSUE TITLE
Defaultwerte der INI

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#18]
Hallo zusammen,
Ich glaube es wäre sinnvoll, einige defaultwerte der INI zu ändern. 
Ich würde MitRand immer auf N setzen (wie in der SekI) und bei den ganzen Anschreiben/Bescheinigungen als Wert für das Datum „F“ wählen, damit man beim Druck gefragt wird und nicht automatisch das Zeugnisdatum genutzt wird.

**Comment by mueller-falko** [comment]
Aber bei den Briefen zur Nichtzulassung und Nichtbestehen ist da V eingetragen. Das würde ja bedeuten, dass ich Zeugnis- und Konferenzdatum setzen muss und bei den nichtzugelassenen/nichtbestehenden "nicht versetzt" eintragen muss, damit das funktioniert, oder? Wäre da nicht zumindest I sinnvoller?

**Comment by M-Plu** [comment]
Da hast du recht. Da wäre K oder I besser. Ich habe jetzt mal I eingetragen, wie du es vorgeschlagen hast.
