### ISSUE TITLE
Anlage 04: Fehler im Feld LaAbschluss

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#2]
Wenn im gedruckten Abschnitt kein Abschluss eingetragen ist und man nach dem Abschluss gefragt wird, funktioniert das Zeugnis für das GY (GE hab ich noch nicht getestet) nur bei der ersten (FOR) und letzten Option (kein Abschluss) korrekt. Bei den anderen beiden Optionen erscheint aus dem Zeugnis der Text "LaAbschluss".
Das liegt daran, dass beim HSA 10 in der Funktion AbschlussErmittlen der Wert 'HA10g' gesetzt wird, im Label LaAbschluss aber nur 'HA10' abgefragt wird. Beim HSA 9 wird in der Funktion 'HA9' gesetzt. Dieser wird aber im Label gar nicht beachtet.

**Comment by M-Plu** [comment]
Habe ich korrigiert.
