### ISSUE TITLE
Anlage 04: Text bei HSA 10 gleichwertigem Abschluss zu nah am Rand

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#3]
Beim Abschluss HA10g ist der Text im Label LaAbschluss so lang, dass er an beiden Seiten fast an den Rand stößt. Ich würde daher eher ein MemoFeld benutzen, dass dann in diesem Fall den Text in zwei Zeilen druckt.

**Comment by M-Plu** [comment]
Ich habe das ersetzt und einen festen Zeilenumbruch eingefügt.
