### ISSUE TITLE
Information über den Zwischenstand der Abiturprüfung

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#30]
Da der nächste Abiturdurchgang naht, möchte ich hier nochmal zur Diskussion stellen, ob es nicht sinnvoll ist, einen Vordruck für die Information über den Zwischenstand der Abiturprüfung (Ergebnisse des 2. ZAA) entweder in das Zeugnispaket zu übernehmen oder zumindest auf der Homepage zum Download bereitzustellen. Es gibt zwar in der ApoGost keine Anlage dazu, aber laut VV 36.1.2 zu §36 müssen die Schüler ja über die Nachprüfungen informiert werden, und ich gehe davon aus, dass die meisten Schulen das nicht in Einzelgesprächen sondern mit einer Ergebnisübersicht machen.
Im Forum kursiert ein Formular, das aus der Abitursammlung stammt und an die aktuellen Vorgaben (keine Abweichungsprüfung mehr) angepasst wurde: https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=13&t=4528&p=26589 
Das könnte man doch vielleicht als Grundlage nehmen?

**Comment by AnneSchueller** [comment]
Dieser Report steht im Prinzip schon im Rahmen der Abitursammlung als Download zur Verfügung. Allerdings stimmt hier der Paragraph nicht. §29(5) statt wie es richtig heißen sollte §29(4) und das Dokument liegt in doppelter Ausfertigung vor:
- Ergebnisse_ZAA2_APO_GOSt_B_V0704_Detail_korrigiert und
- Ergebnisse_ZAA2_APO_GOSt_B_V0704_Detail_neu 

Die Frage wäre, ob man die Abitursammlung für Schild2 nochmal anpackt und ggf. mit in das Zeugnispaket packt oder ob man dann nicht eher Ressourcen dafür freimacht, um die gesamte Abitursammlung auf die Nutzbarkeit in Schild3 zu testen und ggf. aussortiert, anpasst und daraus ein schönes Gesamtpaket als Abiturdownload schnürt.

Ich würde dazu tendieren, den Report zur Information über den Zwischenstand für den nächsten Abiturdurchgang in der Abitursammlung zu lassen.

**Comment by mueller-falko** [comment]
In der Version aus der Abitursammlung ist nicht nur der Paragraph falsch, sondern es wird auch noch die Abweichungsprüfung ausgewiesen. Beide Fehler hat Herr Maßmann in obigem Forumsbeitrag meines Wissens korrigiert. Vielleicht könntest du dann diese Version übernehmen und in der Abitursammlung austauschen.

**Comment by AnneSchueller** [comment]
Ach stimmt, die Abweichungsprüfungen sind ja weggefallen. Ich teste den Report morgen nochmal und schreibe Herrn Maßmann dann an, ob ich seine Version online stellen darf.
Die alten würde ich dann entfernen.
Dann könnte man den Report evtl. doch direkt mit in den Zeugnisdownload packen? Den laden sich die Schulen sicherlich vor dem Abi noch mal erneut runter.

**Comment by M-Plu** [comment]
Sorry, wenn ich mich erst später einklinke. Habt ihr da eine Entscheidung bzgl. des Reports getroffen? Und basiert der auf INI Dateien?

**Comment by AnneSchueller** [comment]
Hallo zusammen,
hier nochmal eine kurze Rückmeldung zu dem Thema:
Wir werden eine überarbeitete Abitursammlung zeitnah auf der Homepage unter dem Reiter Zeugnis-Reports zur Verfügung stellen. Den Report "Ergebnisse_ZAA2_APO_GOSt_B_V0704" werde ich so wie in dem Forenbeitrag übernehmen (also ohne INI Datei). 
Damit schließe ich das Issue hier schonmal.
