### ISSUE TITLE
Falsche Abschnitte aus der INI-Datei

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#31]
Hallo,
in den Anlagen 11, 17 und 18 (beide Versionen) werden im Ereignis GlobalOnCreate die Zeugniseinstellungen von Anlage 10 geladen. Das müsste korrigiert werden.

**Comment by M-Plu** [comment]
Habe ich korrigiert in den dev integriert. Schau nochmal drauf, wenn es OK ist, könnte es raus. Dann kannst du hier schließen.

**Comment by mueller-falko** [comment]
Jetzt klappt alles, wie es soll. Danke
