### ISSUE TITLE
Konfession auf dem Zeugnis

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#33]
Die Zeugnisse geben nur dann eine Konfession auf dem Zeugnis aus, wenn das Feld Schueler['ReligionZeugnisbez'] nicht leer ist. 
Ich dachte bisher, dass in diesem Fall Schueler['ReligionAbk'] gedruckt wird, denn so wurde es mir erklärt und ich meine, das hätte früher so funktioniert. 
In Wuppertal ist das nämlich ein Problem, da es in unserem Konfessionskatalog zentral vorgegebene Konfessionen gibt, die keine Zeugnisbezeichnung eingetragen haben und bei der ich auch nicht die Rechte habe, da etwas einzutragen. 
Ich fände es daher gut, wenn die Zeugnisse so funktionieren würden, dass bei gesetztem Haken und leerer Zeugnisbezeichnung der Eintrag aus dem Katalog unter "Konfession" gedruckt wird.

**Comment by M-Plu** [comment]
Warum werden denn die Bezeichnungen dann nicht zentral ergänzt? 

Es sind halt unvollständig gepflegte Daten. Sonst müsste man auch an anderen Stellen ein Fallback einbauen. 

Eine Abkürzung zu drucken, fände ich auf einem Zeugnis auch unpassend. Und wenn das dazu führt, dass dann aus Abkürzungen Zeugnisbezeichnungen werden (in der DB) ist das ja auch nicht Sinn der Sache, oder?

Wenn Jens, Anne oder Frank das anders sehen, setze ich das aber gerne um.

**Comment by AnneSchueller** [comment]
Ich setze hier mal die Forendiskussion rein für Mitlesen:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=31&t=5445

@mueller-falko : Wenn ich das jetzt richtig verstanden habe, tritt das Problem nur bei der einen Schule auf, die vor kurzem auf Schildzentral umgestiegen ist oder? 

Ich habe bisher noch nie Beschwerden diesbezüglich gehabt und würde es dann auch bei dem Feld ReligionZeugnisbez belassen.

**Comment by mueller-falko** [comment]
Bei der Forendiskussion geht es um etwas anderes. Da scheint es ein technisches Problem bei der Schule zu geben, die vor kurzem auf SchildZentral gewechselt hat.
In diesem Issue ging es mir um die generelle Programmierung und die Frage, wie der Report damit umgeht, wenn die Zeugnisbezeichnung leer ist, da in Wuppertal bei den zentralen Katalogeinträgen das Feld nicht belegt ist. Ich kann Michaels Argumente gut nachvollziehen und werde mal schauen, wen ich in Wuppertal ansprechen muss, damit der Katalog entsprechend ergänzt wird.
Für mich wäre das Issue damit erledigt.
