### ISSUE TITLE
Weitere Vornamen Anlage 5b

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#34]
siehe: https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=16&t=5481&p=32036#p32036
Die Funktionen ZeugnisVornameDruck und ZeugnisVornameNachnameDruck fehlen in der Anlage, daher hat der INI-Schalter keine Wirkung.

**Comment by M-Plu** [comment]
Das lag daran, dass ursprünglich nur die Ersetzungen aus den Serienbriefen genutzt wurden und ich die nicht anpassen wollte. Das habe ich nun gemacht. Jetzt sollten auch die INI Einstellungen dort greifen.
