### ISSUE TITLE
Anlage 04: merkwürdiges Verhalten des Reportdesigners

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#4]
Wenn ich in Anlage 4 zu den Berechnungen wechsel, werden mir procedure Seite1OnPrint und procedure AbschlussErmitteln rot angezeigt (Fehlermeldungen siehe Screenshots).
Der Druck funktioniert aber einwandfrei.
Wenn ich procedure AbschlussErmitteln kompiliere, verschwinden die Fehlermeldungen. Nach einem Wechsel in die Vorschau oder auch nach Speichern/Schliessen und neu öffnen sind sie wieder da. 
Ist das nur bei mir so?
![RD-rot1](https://user-images.githubusercontent.com/60217031/100726145-dbd97400-33c4-11eb-9ebf-be00239cc57e.jpg)
![RD-rot2](https://user-images.githubusercontent.com/60217031/100726149-de3bce00-33c4-11eb-8abe-7bbf149f7bfd.jpg)

**Comment by M-Plu** [comment]
Ist bei mir auch so, warum weiß ich nicht. Müsste man mal debuggen (Dr. Richter oder so).

**Comment by M-Plu** [comment]
Problem gelöst: Procedure gelöscht und neu angelegt.
