### ISSUE TITLE
Anlage 4: Abschluss

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#5]
Der eingetragene Abschluss erscheint nicht, wenn kein Versetzungsvermerk eingetragen ist. Ist das Absicht?

**Comment by M-Plu** [comment]
Ich habe damals an die EF gedacht, da ist bei einem Abschluss am Ende des Schuljahres immer eine Versetzungsentscheidung eingetragen. in Der Q1 und vor allem in der Q2.1 muss das nicht sein. Ich nehme das als Einschränkung überall raus, oder wie siehst du das?

**Comment by mueller-falko** [comment]
Ich würde die Einschränkung entfernen. Es kann ja sein, dass jemand sein Abschlusszeugnis kurz vor Schuljahresende bekommt und noch keine Versetzungsberechnung durchgeführt wurde. Vielleicht gibt es ja auch Schulen, die die Versetzungsberechnung von Schild gar nicht nutzen und sich auf den tollen Report eines gewissen M.P. verlassen ;-)

**Comment by M-Plu** [comment]
Ich habe das jetzt aus Anlage 4 entfernt. Die FHR wird ja in der Q1 eher über die zugehörige Datenquelle FHR zugewiesen. Daher schaue ich dort nach statt im Halbjahr.
