### ISSUE TITLE
Anlage 3 Unterschiede in der Darstellung bei fehlender Note

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#6]
In Anlage 3 werden im Notenfeld vom Vertiefungsfach nur 3 "-" angezeigt wenn das Notenfeld (aus welchen Gründen auch immer) leer ist, bei allen anderen Fächern werden aber 20 "-" angezeigt. Das sollte vielleicht einheitlich sein.

**Comment by M-Plu** [comment]
Ist korrigiert. Im der Originalcode ist wohl mal aus den Q1 Zeugnissen kopiert worden. Da waren die Spalten enger. Wenn der Text leer ist, wird nun nichts mehr an Text gesetzt und das Notenfeld verhält sich wie die anderen Notenfelder.
