### ISSUE TITLE
Frage zur Auswahl des alten Abschlusses bei Abgangszeugnissen

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild-NRW-Zeugnisse-Sek2#9]
SuS einer Gesamtschule bekommen wenn sie nicht in die Oberstufe gehen und entsprechende Leistungen erbracht haben den Mittleren Abschluss, mit der Berechtigung zum Besuch der gymnasialen Oberstufe (EF) attestiert, d.h. FORQ bzw. MAQ. SuS die weiter machen erhalten lediglich ein Versetzungszeugnis. Wenn diese SuS die Schule ohne FHR oder Abi verlassen kann als maximaler alter Abschluss nur FOR bzw MA ausgewählt werden. Der Qualifikationsvermerk also FORQ bzw MAQ wird nicht ausgewiesen. Müsste das nicht auf einem Abgangszeugnis mit vermerkt werden. Ich hab aber nirgendwo weder in der  BASS noch APO GOSt Hinweise dazu finden können.

**Comment by M-Plu** [comment]
Meinem Kenntnisstand nach erhalten die SuS am Ende der 10 der Gesamtschule ein Abschlusszeugnis und müssen sich neu an der Schule für die Oberstufe anmelden. 

Wenn ein Schüler später ein Zeugnis aus der Oberstufe vorlegt, ist klar, dass er die Qualifikation für die Oberstufe erworben vorher mal erworben haben muss. Der Abschluss ist aber nicht eindeutig (je nach Laufbahn und Noten am Gymnasium oder Gesamtschule) und wird daher notiert.
